### ISSUE TITLE
Julia v1.2 support?

### ISSUE THREAD

**Issue by andyferris** [visr/LasIO.jl#23]
I'm not sure if this is just me, but I can't get LasIO to install on Julia 1.2:

```
(v1.2) pkg> add LasIO
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package LasIO [570499db]:
 LasIO [570499db] log:
 ├─possible versions are: [0.1.0, 0.2.0-0.2.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 0.2.0-0.2.1]
 └─restricted by compatibility requirements with FixedPointNumbers [53c48c17] to versions: uninstalled — no versions left
   └─FixedPointNumbers [53c48c17] log:
     ├─possible versions are: [0.5.0-0.5.3, 0.6.0-0.6.1] or uninstalled
     └─restricted to versions 0.6.1 by an explicit requirement, leaving only versions 0.6.1
```

I also note that this package hasn't used the new Project.toml files, but rather the older REQUIRE format.

**Comment by visr** [comment]
Hmm I'm surprised it wouldn't work. But it was about time to add Project.toml haha. In #24 I also bumped FixedPointNumbers to at least [release v0.6.0](https://github.com/JuliaMath/FixedPointNumbers.jl/releases), not 100% sure it is needed, but that release switched to Project.toml as well, so that might help.

**Comment by andyferris** [comment]
Thanks @visr
